apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-volume-test
  namespace: skala-practice
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  volumeName: efs-volume-test

