apiVersion: v1
kind: Service
metadata:
  name: sk000-green
  namespace: skala-practice
spec:
  selector:
    app: sk000-ingress-green
    version: 2.0.0
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: mgmt
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP


