{
 "title": "HTTP Server Requests (skala-my-app)",
 "tags": [
  "spring",
  "prometheus",
  "http"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(kube_pod_labels{namespace=\"skala-practice\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Raw Count (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{namespace=\"skala-practice\", pod=~\"$deployment-.*\"})",
     "legendFormat": "Total Count"
    }
   ]
  },
  {
   "title": "Rate (per second) per Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{namespace=\"skala-practice\", pod=~\"$deployment-.*\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Avg Rate (All Pods)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "reqps", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(http_server_requests_seconds_count{namespace=\"skala-practice\", pod=~\"$deployment-.*\"}[1m]))",
     "legendFormat": "Avg req/s"
    }
   ]
  },
  {
   "title": "Total Request Rate (req/s)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"skala-practice\", pod=~\"$deployment-.*\"}[1m]))",
     "legendFormat": "Total Req/s"
    }
   ]
  }
 ]
}