apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk000-my-app
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk000-my-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/prometheus'
        update: f6574ffbea146753e12a0d8e3247dff3
      labels:
        app: sk000-my-app
    spec:
      serviceAccountName: default
      containers:
      - name: webserver
        image: amdp-registry.skala-ai.com/skala25a/sk000-webserver:2.0.0
        imagePullPolicy: Always
        env:
        - name: LOGGING_LEVEL
          value: DEBUG
        - name: USER_NAME
          value: sk000
