apiVersion: v1
kind: Service
metadata:
  name: sk000-blue
  namespace: skala-practice
spec:
  selector:
    app: sk000-zero-dtd-test
    version: 1.0.0
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: mgmt
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP


