apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk000-blue
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk000-zero-dtd-test
      version: 1.0.0
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
        update: 77d360a1ea2f4c15853e7bf4f5914343
      labels:
        app: sk000-zero-dtd-test
        version: 1.0.0
    spec:
      containers:
      - name: webserver
        image: amdp-registry.skala-ai.com/skala25a/skala-webserver:1.0.0
        imagePullPolicy: Always
        env:
        - name: LOGGING_LEVEL
          value: DEBUG
        - name: USER_NAME
          value: sk000
        - name: NAMESPACE
          value: skala-practice
