apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-sc-team-14-postgresql
  namespace: sk-team-14
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: gp2

