apiVersion: apps/v1
kind: Deployment
metadata:
  name: himang10-deploy-test
  namespace: skala-practice
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8081'
    prometheus.io/path: '/actuator/prometheus'
    update: 7a4d145eaf266c9c6f556cce11c1c6f0
  labels:
    app: himang10-deploy-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: himang10-deploy-test
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
      labels:
        app: himang10-deploy-test
    spec:
      serviceAccountName: default
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: skala-k8s-practice
                operator: In
                values:
                - "yes"
      tolerations:
      - effect: 
        key: skala-k8s-practice
        operator: Equal
        value: "yes"
      containers:
      - name: webserver
        image: amdp-registry.skala-ai.com/skala25a/himang10-webserver:1.0.0
        imagePullPolicy: Always
        env:
        - name: USER_NAME
          value: himang10

        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: dev-db-secret
              key: database.url
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: dev-db-secret
              key: database.user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-db-secret
              key: database.password

