apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk003-myfirst-api-server
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk003-myfirst-api-server
  template:
    metadata:
      labels:
        app: sk003-myfirst-api-server
    spec:
      serviceAccountName: default
      containers:
        - name: myfirst-api-server
          image: amdp-registry.skala-ai.com/skala25a/sk003-myfirst-api-server:1.0.0
          imagePullPolicy: Always
