apiVersion: v1
kind: Secret
metadata:
  name: amdp-registry
  namespace: class-1      # 원하는 namespace 지정
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "amdp-registry.skala-ai.com": {
          "username": "robot$skala-professor",
          "password": "UNYMp8t89kwIIMwsSmOJJ9d3pMoy14n8",
          "auth": "cm9ib3Qkc2thbGEtcHJvZmVzc29yOlVOWU1wOHQ4OWt3SUlNd3NTbU9KSjlkM3BNb3kxNG44"
        }
      }
    }
