apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk000-replicaset-test
  namespace: skala-practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sk000-replicaset-test
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
        update: 41ea7741d6ea2b0a77eb2c75861ae389
      labels:
        app: sk000-replicaset-test
    spec:
      serviceAccountName: default
      containers:
      - name: webserver
        image: amdp-registry.skala-ai.com/skala25a/sk000-webserver:1.0.0
        imagePullPolicy: Always
        env:
        - name: LOGGING_LEVEL
          value: DEBUG
        - name: USER_NAME
          value: sk000
        - name: NAMESPACE
          value: skala-practice
