apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk000-volume-test
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk000-volume-test
  template:
    metadata:
      annotations:
        update: 10cfd3cad63aa9baa7e7c4ccb404e3a6
      labels:
        app: sk000-volume-test
    spec:
      serviceAccountName: default
      containers:
      - name: storage-test
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
          - echo "Hello from busybox" > /data/hello.txt && sleep infinity
        volumeMounts:
        - name: efs-volume
          mountPath: /data
      volumes:
      - name: efs-volume
        persistentVolumeClaim:
          claimName: sk000-efs-sc-volume-test

